// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_nICKDlYyIyHzlYRTmVCbIyxsnFA6q0',
    appId: '1:968710231541:web:322d82fece5bbef07f7cbc',
    messagingSenderId: '968710231541',
    projectId: 'fir-store-e4c8e',
    authDomain: 'fir-store-e4c8e.firebaseapp.com',
    storageBucket: 'fir-store-e4c8e.appspot.com',
    measurementId: 'G-H60KNHVKW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsaIROK2mv9QSVXPEDvSVEvKRMd2IhWSQ',
    appId: '1:968710231541:android:60a3702b59679d537f7cbc',
    messagingSenderId: '968710231541',
    projectId: 'fir-store-e4c8e',
    storageBucket: 'fir-store-e4c8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApi1cixiXGb9SfnZUn2XoiynW0frLgl4w',
    appId: '1:968710231541:ios:e289839040e4eec27f7cbc',
    messagingSenderId: '968710231541',
    projectId: 'fir-store-e4c8e',
    storageBucket: 'fir-store-e4c8e.appspot.com',
    iosClientId: '968710231541-neh5cn9d51njpjr0k2ndusikjemihg0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApi1cixiXGb9SfnZUn2XoiynW0frLgl4w',
    appId: '1:968710231541:ios:e289839040e4eec27f7cbc',
    messagingSenderId: '968710231541',
    projectId: 'fir-store-e4c8e',
    storageBucket: 'fir-store-e4c8e.appspot.com',
    iosClientId: '968710231541-neh5cn9d51njpjr0k2ndusikjemihg0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicFlutterApp',
  );
}
